[package]
name = "kfc_gh"
version = "0.1.0"
authors = ["Evgeny Fomin <fominok@hotmail.com>"]

[dependencies]
hyper = "0.11.27"
futures = "0.1"
tokio-core = "0.1"
failure = "0.1.1"
hyper-tls = "0.1.3"
tokio-io = "0.1"